name: Publish
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CLICOLOR_FORCE: 1
jobs:
  build:
    name: Publish for ${{ matrix.os.binary_target }}
    runs-on: ${{ matrix.os.platform }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - platform: ubuntu-latest
            binary_target: x86_64-unknown-linux-musl
            cross: "true"
          - platform: ubuntu-latest
            binary_target: x86_64-unknown-linux-gnu
            cross: "true"
          - platform: windows-latest
            binary_target: x86_64-pc-windows-msvc
          - platform: macos-latest
            binary_target: x86_64-apple-darwin
          
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install depencencies for ubuntu-latest
      if: matrix.os.platform == 'ubuntu-latest'
      run: sudo apt-get install musl-tools pkg-config libssl-dev

    - name: Set PKG_CONFIG_PATH
      if: matrix.os.platform == 'ubuntu-latest'
      run: export PKG_CONFIG_PATH=/usr/lib/pkgconfig
    
    - name: Set OPENSSL_DIR
      if: matrix.os.platform == 'ubuntu-latest'
      run: export OPENSSL_DIR=/usr/local/ssl

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust_toolchain }}
        target: ${{ matrix.os.binary_target}}
        profile: minimal
        override: true

    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make

    - name: Make zip-release-ci-flow
      id: zip-release-ci-flow
      run: cargo make --disable-check-for-updates zip-release-ci-flow
      env:
          TARGET: ${{ matrix.os.binary_target }}
          CROSS: ${{ matrix.os.cross }}

    - name: Upload Binaries
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.zip-release-ci-flow.outputs.dist_file_path }}
        # tag: ${{ github.ref }}
        tag: v${{ steps.zip-release-ci-flow.outputs.dist_version }}
        overwrite: true
        file_glob: true