name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    name: create-release job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with: 
          config: cliff.toml
          args: --latest
        env:
          OUTPUT: CHANGELOG.md
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Get binary name
        uses: dangdennis/toml-action@v1.3.0
        id: read_cargo_toml
        with:
          file: "Cargo.toml"
          field: "package.name"
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ steps.read_cargo_toml.outputs.value }}
          archive: $bin-$tag-$target
          tar: unix
          zip: windows
          checksum: sha256
          include: README.md,LICENSE
          token: ${{ secrets.GITHUB_TOKEN }}